# Generated by Django 5.1.7 on 2025-03-31 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVideojuegos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuegos',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videojuegos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='recursos/'),
        ),
    ]
