# Generated by Django 5.1.7 on 2025-03-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVideojuegos', '0002_videojuegos_video_alter_videojuegos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuegos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
