# Generated by Django 5.1.7 on 2025-04-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVideojuegos', '0003_alter_videojuegos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuegos',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
