# Generated by Django 5.1.7 on 2025-04-02 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVideojuegos', '0004_alter_videojuegos_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuegos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='recursos/imagenes/'),
        ),
    ]
