# Generated by Django 5.1.7 on 2025-04-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVideojuegos', '0005_alter_videojuegos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuegos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
